import React from 'react'
import type { Metadata } from "next";
import Header from '@/components/public/Header';
import Footer from '@/components/public/Footer';

export const metadata: Metadata = {
    title: "Hedgeon Finance",
    description: "Generated by create next app",
};

function AuthLayout({ children }: { children: React.ReactNode }) {
    return (
        <section>
            {children}
        </section>
    )
}

export default AuthLayout
